spring.application.name=order-api

# Database Connection (Supabase Pooler - JDBC Format)
spring.datasource.url=jdbc:postgresql://aws-1-ap-southeast-2.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.zzjwbxsxvrugfiixbbuz
spring.datasource.password=k2FM1faip2VyfRmQ
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate Configuration
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect